version: 2.1

jobs:
  build:
    docker:
      - image: juanmaaf/moneycontroller
    steps:
      - checkout
      - run:
          name: Ejecutar los test con make
          command: make test

workflows:
  version: 2
  test:
    jobs:
      - test